### ISSUE TITLE
ConnectionErrors take too long and crash

### ISSUE THREAD

**Issue by DJTOMATO** [eeemoon/perchance#1]
Hi, I've tried this and worked fine with a few hiccups there and here. but since last week it has become really hard to get one image to work.

```py
ConnectionError: 
Traceback (most recent call last):
  File "/home/glas/test/lib/python3.11/site-packages/perchance/imagegen.py", line 144, in _fetch_key
    await t.tick()
  File "/home/glas/test/lib/python3.11/site-packages/perchance/utils.py", line 17, in tick
    raise self._exc
perchance.errors.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<eval command - snippet #3>", line 14, in generate_image
  File "/home/glas/test/lib/python3.11/site-packages/perchance/imagegen.py", line 178, in image
    await self.refresh()
  File "/home/glas/test/lib/python3.11/site-packages/perchance/aigen.py", line 36, in refresh
    self._key = await cls._fetch_key()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glas/test/lib/python3.11/site-packages/perchance/imagegen.py", line 151, in _fetch_key
    raise errors.ConnectionError()
perchance.errors.ConnectionError
```

Any ideas how to further debug this issue? Not sure if i am being blocked, the API is overloaded, etc

**Comment by DJTOMATO** [comment]
Can't confirm it yet, but when I open the website from my browser and start making prompts from there for some reason the generator seems to start working again, could be a coincidence. although devices are different they're sharing the same external ip, maybe there are issues getting the key?

**Comment by eeemoon** [comment]
Hello, I think perchance was overloaded, so it exceed the timeout of 20 seconds. It happens sometimes even without API.

**Comment by DJTOMATO** [comment]
There's definitively something we're missing here.  {"status":"failed_verification","reason":"token_required"}

the token is obtained via a cloudflare turnstile response. I have to visit the website manually every few hours for the script to work which it has become annoying at this point.

Was doing some research on turnstile bypass but can't find anything that works with headless mode.

https://github.com/manh9011/Perchance-T2I-Desktop/blob/c5a9a9a4b2dc5f377a8505e917980ccf73d470b8/Perchance/PerchanceBox.cs#L248
This guy managed to handle it but it's in C#.

Would you give it a check when you have the chance?

**Comment by LeonardoNettoPY** [comment]
I have the same problem, the API is: 0661192abeaa3c76d2659d694a1238d6

**Comment by eeemoon** [comment]
Should be fixed now
